@actor("10000000-0000-4000-8000-000000000010", type:"Human")
@icon("/iconify/mdi/account-outline.svg")
model Traveler {}

@actor("10000000-0000-4000-8000-000000000011", type:"InternalSystem")
@icon("/iconify/mdi/magnify.svg")
model DiscoveryService {}

@actor("10000000-0000-4000-8000-000000000012", type:"ExternalSystem")
@icon("/iconify/mdi/office-building-outline.svg")
model AccommodationInformationProvider {}
