@actor("f16826c2-b7ca-4ab3-8080-8a79fc9b2d74", type:"Human")
@icon("/iconify/mdi/account-hard-hat-outline.svg")
model WarehouseOperator {}

@actor("84b778d9-6610-4e8f-9f90-00fea5531fe4", type:"InternalSystem")
@icon("/iconify/mdi/truck-delivery-outline.svg")
model FulfillmentService {}

@actor("bd60ee91-2cd5-43f4-95a1-5dd5036b598d", type:"ExternalSystem")
@icon("/iconify/mdi/truck-fast-outline.svg")
model DeliveryCarrier {}
