@actor("20000000-0000-4000-8000-000000000012", type:"Human")
@icon("/iconify/mdi/account-outline.svg")
model Traveler {}

@actor("20000000-0000-4000-8000-000000000013", type:"InternalSystem")
@icon("/iconify/mdi/clipboard-text-cog-outline.svg")
model ReservationService {}

@actor("20000000-0000-4000-8000-000000000014", type:"ExternalSystem")
@icon("/iconify/mdi/office-building-outline.svg")
model AccommodationReservationSystem {}
