@actor("30000000-0000-4000-8000-000000000013", type:"Human")
@icon("/iconify/mdi/account-tie-outline.svg")
model PropertyManager {}

@actor("30000000-0000-4000-8000-000000000014", type:"InternalSystem")
@icon("/iconify/mdi/calendar-cog-outline.svg")
model InventoryManagementSystem {}

@actor("30000000-0000-4000-8000-000000000015", type:"ExternalSystem")
@icon("/iconify/mdi/swap-horizontal.svg")
model DistributionSystem {}
